Extra field in transaction structure
ElrondNetwork/elrond-proxy-go pull request #102
Opened 2020-10-27 07:11 UTC by miiu96

Added field `options` in transaction structure

2020-10-27 07:52 UTC, bogdan-rosianu approved these changes

2020-11-02 18:59 UTC, andreibancioiu approved these changes

2020-11-10 08:14 UTC, bogdan-rosianu requested changes
PR is fine, but don't merge until the elrond-go branch is merged

2020-11-13 20:01 UTC, andreibancioiu commented
> PR is fine, but don't merge until the elrond-go branch is merged

Let's merge it though - two-ways compatible, right? Or not?

2020-11-13 20:01 UTC, andreibancioiu approved these changes

2020-11-16 12:14 UTC, bogdan-rosianu approved these changes

2020-11-16 18:09 UTC, merged