EN-8219: ESDT API endpoints
ElrondNetwork/elrond-proxy-go pull request #105
Opened 2020-11-18 15:41 UTC by bogdan-rosianu

2020-11-18 17:45 UTC, sasurobert submitted a review, later dismissed

2020-11-23 15:02 UTC, miiu96 requested changes

2020-11-23 15:37 UTC, bogdan-rosianu commented on api/address/routes.go
> +	router.GET("/:address/esdt/:tokenName", GetESDTTokenData)
done

2020-11-23 15:37 UTC, bogdan-rosianu commented on api/address/routes.go
> +	tokenName := c.Param("tokenName")
done

2020-11-23 15:37 UTC, bogdan-rosianu commented on api/errors/errors.go
> +var ErrEmptyTokenName = errors.New("token name is empty")
done

2020-11-23 15:46 UTC, miiu96 commented on api/errors/errors.go
> +var ErrEmptyTokenIdentifier = errors.New("token name is empty")
please change also the message of error

2020-11-23 15:47 UTC, bogdan-rosianu commented on api/errors/errors.go
> +var ErrEmptyTokenIdentifier = errors.New("token name is empty")
done

2020-11-23 15:48 UTC, miiu96 approved these changes

2020-11-24 15:36 UTC, sasurobert approved these changes

2020-11-26 19:42 UTC, merged