Activation epochs endpoint
ElrondNetwork/elrond-proxy-go pull request #196
Opened 2021-04-05 10:57 UTC by mateigraura

Add new endpoint `network/enable-epochs` in order to retrieve activation epochs metric from observers

2021-04-06 10:06 UTC, bogdan-rosianu requested changes

2021-04-06 10:06 UTC, bogdan-rosianu commented on cmd/proxy/config/apiConfig/v1_0.toml
> +    { Name = "/enable-epochs", Open = true, Secured = false, RateLimit = 0 }
add also in `v_next`

2021-04-06 10:06 UTC, bogdan-rosianu commented on process/nodeStatusProcessor.go
> +// GetEnableEpochsMetrics will simply forward the activation epochs config metrics from an observer in the given shard
drop the `in the given shard`

2021-04-06 14:53 UTC, mateigraura commented on cmd/proxy/config/apiConfig/v1_0.toml
> +    { Name = "/enable-epochs", Open = true, Secured = false, RateLimit = 0 }
done

2021-04-06 14:53 UTC, mateigraura commented on process/nodeStatusProcessor.go
> +// GetEnableEpochsMetrics will simply forward the activation epochs config metrics from an observer in the given shard
done

2021-04-07 13:03 UTC, bogdan-rosianu submitted a review, later dismissed

2021-04-08 16:39 UTC, miiu96 commented on process/nodeStatusProcessor.go
>  // NodeStatusPath represents the path where an observer exposes all the issued ESDTs
Add this API route also in README.md

2021-04-09 09:15 UTC, mateigraura commented on process/nodeStatusProcessor.go
>  // NodeStatusPath represents the path where an observer exposes all the issued ESDTs
done

2021-04-09 09:16 UTC, miiu96 approved these changes

2021-04-09 09:16 UTC, bogdan-rosianu approved these changes

2021-04-15 13:08 UTC, gabi-vuls approved these changes
System test passed

2021-04-20 15:02 UTC, merged