get all esdts roles
ElrondNetwork/elrond-proxy-go pull request #264
Opened 2021-08-06 14:17 UTC by miiu96

- Added a new API route /address/:address that will return all esdts tokens with roles

2021-08-06 14:46 UTC, bogdan-rosianu requested changes

2021-08-06 14:46 UTC, bogdan-rosianu commented on api/groups/baseAccountsGroup.go
> +func (group *accountsGroup) getESDTsRoles(c *gin.Context) {
add unit tests

2021-08-06 14:46 UTC, bogdan-rosianu commented on process/accountProcessor.go
> +func (ap *AccountProcessor) GetESDTsRoles(address string) (*data.GenericAPIResponse, error) {
don't forget about comments for exported members

2021-08-06 14:46 UTC, bogdan-rosianu commented on process/accountProcessor.go
> +		apiPath := AddressPath + address + "esdts/roles"
extract constant. also, bug: there's no `/` between address and `esdts/roles`

2021-08-06 14:46 UTC, bogdan-rosianu commented on process/accountProcessor.go
> +func (ap *AccountProcessor) GetESDTsRoles(address string) (*data.GenericAPIResponse, error) {
add unit test

2021-08-09 08:59 UTC, iulianpascalau approved these changes

2021-08-09 13:10 UTC, sasurobert approved these changes

2021-08-09 15:55 UTC, merged