Export internal headers
ElrondNetwork/elrond-proxy-go pull request #287
Opened 2022-01-14 17:03 UTC by ssd04

2022-01-18 10:11 UTC, bogdan-rosianu requested changes

2022-01-25 15:51 UTC, ssd04 commented on process/blockProcessor_test.go
> +		Name:  "a test struct to be send",
:+1:

2022-01-25 15:51 UTC, ssd04 commented on process/errors.go
> +var ErrInvalidOutportFormat = errors.New("the outport format type is invalid")
:+1:

2022-01-25 15:52 UTC, ssd04 commented on api/groups/baseInternalGroup.go
> +	blockByHashResponse, err := group.facade.GetInternalMiniBlockByHash(shardID, hash, common.Internal)
changed with miniBlock prefix

2022-01-25 15:52 UTC, ssd04 commented on api/groups/baseInternalGroup.go
> +	blockByHashResponse, err := group.facade.GetInternalMiniBlockByHash(shardID, hash, common.Proto)
changed with miniBlock prefix

2022-01-25 15:52 UTC, ssd04 commented on data/block.go
> +	Block interface{} `json:"miniblock"`
done

2022-01-25 15:53 UTC, ssd04 commented on process/blockProcessor_test.go
> +func TestBlockProcessor_GetInternalBlockByNonceInvalidOutportFormat_ShouldFail(t *testing.T) {
renaming done

2022-01-25 15:53 UTC, ssd04 commented on process/blockProcessor.go
> +func getOutportStr(format common.OutportFormat) (string, error) {
done

2022-01-25 15:54 UTC, ssd04 commented on common/constants.go
> +type OutportFormat uint8
:+1:

2022-02-14 11:58 UTC, bogdan-rosianu submitted a review, later dismissed

2022-02-22 10:29 UTC, AdoAdoAdo submitted a review, later dismissed

2022-03-01 14:03 UTC, AdoAdoAdo approved these changes

2022-03-01 15:02 UTC, merged